# -*- coding: utf-8 -*-
"""denoising audio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z-0vtJPTlT4XuMX9ONSeOLL2Q2iixf7c
"""


import librosa
import soundfile as sf
import noisereduce as nr

audio_data, sample_rate = librosa.load("/content/denoised_audio.wav", sr=None)

reduced_noise = nr.reduce_noise(y=audio_data, sr=sample_rate)


sf.write("denoised_audio.wav", reduced_noise, sample_rate) 