# -*- coding: utf-8 -*-
"""transcription.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VmBE3MG30bVnLKFln4M0AkFdmDNb3VkH
"""

# First install-> !pip install SpeechRecognition==3.10.0

import speech_recognition as sr

r = sr.Recognizer()

audio_file = sr.AudioFile("/content/sample_data/denoised_audio (1).wav") 

with audio_file as source:
    audio_data = r.record(source)
    text = r.recognize_google(audio_data)

print(text)

with open("output.txt", "w") as f:
    f.write(text)

print("Output saved to output.txt")